<AppInterface>:
    orientation: "vertical"


    Accordion:
        orientation: "vertical"

        AccordionItem:
            title: "Inputs"
            collapse: 0

        AccordionItem:
            title: "DD-1801 (ICAO)"
            collapse: 1

        AccordionItem:
            title: "1-800-wx-brief"
            collapse: 1

        AccordionItem:
            title: "In Flight"
            collapse: 1

